version: '3'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    command: >
      etcd
      --name etcd-node
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"

  u-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - etcd
